// <auto-generated />
using System;
using CRMBanks.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRMBanks.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260228114130_create_project")]
    partial class create_project
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankRequest", b =>
                {
                    b.Property<int>("BanksId")
                        .HasColumnType("integer")
                        .HasColumnName("banks_id");

                    b.Property<int>("RequestsId")
                        .HasColumnType("integer")
                        .HasColumnName("requests_id");

                    b.HasKey("BanksId", "RequestsId")
                        .HasName("pk_bank_request");

                    b.HasIndex("RequestsId")
                        .HasDatabaseName("ix_bank_request_requests_id");

                    b.ToTable("bank_request", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Auth2F", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("DateTimeSendCode")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_send_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth2fs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth2fs_user_id");

                    b.ToTable("auth2fs", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_banks");

                    b.ToTable("banks", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AzSana")
                        .HasColumnType("integer")
                        .HasColumnName("az_sana");

                    b.Property<int>("AzSum")
                        .HasColumnType("integer")
                        .HasColumnName("az_sum");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<double>("Foiz")
                        .HasColumnType("double precision")
                        .HasColumnName("foiz");

                    b.Property<string>("Infoprot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("infoprot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ToSana")
                        .HasColumnType("integer")
                        .HasColumnName("to_sana");

                    b.Property<int>("ToSum")
                        .HasColumnType("integer")
                        .HasColumnName("to_sum");

                    b.Property<int>("TypeCreditId")
                        .HasColumnType("integer")
                        .HasColumnName("type_credit_id");

                    b.Property<string>("TypeSumId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_sum_id");

                    b.Property<int?>("TypeSumId1")
                        .HasColumnType("integer")
                        .HasColumnName("type_sum_id1");

                    b.HasKey("Id")
                        .HasName("pk_credits");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_credits_bank_id");

                    b.HasIndex("TypeCreditId")
                        .HasDatabaseName("ix_credits_type_credit_id");

                    b.HasIndex("TypeSumId1")
                        .HasDatabaseName("ix_credits_type_sum_id1");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AzSana")
                        .HasColumnType("integer")
                        .HasColumnName("az_sana");

                    b.Property<int>("AzSum")
                        .HasColumnType("integer")
                        .HasColumnName("az_sum");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<double>("Foiz")
                        .HasColumnType("double precision")
                        .HasColumnName("foiz");

                    b.Property<string>("Infoprot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("infoprot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ToSana")
                        .HasColumnType("integer")
                        .HasColumnName("to_sana");

                    b.Property<int>("ToSum")
                        .HasColumnType("integer")
                        .HasColumnName("to_sum");

                    b.Property<int>("TypeDepositId")
                        .HasColumnType("integer")
                        .HasColumnName("type_deposit_id");

                    b.Property<string>("TypeSumId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_sum_id");

                    b.Property<int?>("TypeSumId1")
                        .HasColumnType("integer")
                        .HasColumnName("type_sum_id1");

                    b.HasKey("Id")
                        .HasName("pk_deposits");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_deposits_bank_id");

                    b.HasIndex("TypeDepositId")
                        .HasDatabaseName("ix_deposits_type_deposit_id");

                    b.HasIndex("TypeSumId1")
                        .HasDatabaseName("ix_deposits_type_sum_id1");

                    b.ToTable("deposits", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardId")
                        .HasColumnType("integer")
                        .HasColumnName("card_id");

                    b.Property<int?>("CreditId")
                        .HasColumnType("integer")
                        .HasColumnName("credit_id");

                    b.Property<int?>("DepositId")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_products_card_id");

                    b.HasIndex("CreditId")
                        .HasDatabaseName("ix_products_credit_id");

                    b.HasIndex("DepositId")
                        .HasDatabaseName("ix_products_deposit_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<int>("Srok")
                        .HasColumnType("integer")
                        .HasColumnName("srok");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Sum")
                        .HasColumnType("integer")
                        .HasColumnName("sum");

                    b.Property<int?>("TypeProductId")
                        .HasColumnType("integer")
                        .HasColumnName("type_product_id");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_requests_product_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_requests_region_id");

                    b.HasIndex("TypeProductId")
                        .HasDatabaseName("ix_requests_type_product_id");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.RequestAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_request_actions");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_request_actions_bank_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_actions_request_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_request_actions_user_id");

                    b.ToTable("request_actions", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_type_credits");

                    b.ToTable("type_credits", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeDeposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_type_deposits");

                    b.ToTable("type_deposits", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("TypeCreditId")
                        .HasColumnType("integer")
                        .HasColumnName("type_credit_id");

                    b.Property<int?>("TypeDepositId")
                        .HasColumnType("integer")
                        .HasColumnName("type_deposit_id");

                    b.HasKey("Id")
                        .HasName("pk_type_products");

                    b.HasIndex("TypeCreditId")
                        .HasDatabaseName("ix_type_products_type_credit_id");

                    b.HasIndex("TypeDepositId")
                        .HasDatabaseName("ix_type_products_type_deposit_id");

                    b.ToTable("type_products", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeSum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_type_sums");

                    b.ToTable("type_sums", (string)null);
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AzSum")
                        .HasColumnType("integer")
                        .HasColumnName("az_sum");

                    b.Property<int>("BankId")
                        .HasColumnType("integer")
                        .HasColumnName("bank_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("ToSum")
                        .HasColumnType("integer")
                        .HasColumnName("to_sum");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("BankId")
                        .HasDatabaseName("ix_users_bank_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RegionUser", b =>
                {
                    b.Property<int>("RegionsId")
                        .HasColumnType("integer")
                        .HasColumnName("regions_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("RegionsId", "UsersId")
                        .HasName("pk_region_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_region_user_users_id");

                    b.ToTable("region_user", (string)null);
                });

            modelBuilder.Entity("BankRequest", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Bank", null)
                        .WithMany()
                        .HasForeignKey("BanksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_request_banks_banks_id");

                    b.HasOne("CRMBanks.Core.Entities.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_request_requests_requests_id");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Auth2F", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.User", "Users")
                        .WithMany("Auth2Fs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth2fs_users_user_id");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Credit", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credits_banks_bank_id");

                    b.HasOne("CRMBanks.Core.Entities.TypeCredit", "TypeCredit")
                        .WithMany("Credits")
                        .HasForeignKey("TypeCreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credits_type_credits_type_credit_id");

                    b.HasOne("CRMBanks.Core.Entities.TypeSum", "TypeSum")
                        .WithMany("Credits")
                        .HasForeignKey("TypeSumId1")
                        .HasConstraintName("fk_credits_type_sums_type_sum_id1");

                    b.Navigation("Bank");

                    b.Navigation("TypeCredit");

                    b.Navigation("TypeSum");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Deposit", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_banks_bank_id");

                    b.HasOne("CRMBanks.Core.Entities.TypeDeposit", "TypeDeposit")
                        .WithMany("Deposits")
                        .HasForeignKey("TypeDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deposits_type_deposits_type_deposit_id");

                    b.HasOne("CRMBanks.Core.Entities.TypeSum", "TypeSum")
                        .WithMany("Deposits")
                        .HasForeignKey("TypeSumId1")
                        .HasConstraintName("fk_deposits_type_sums_type_sum_id1");

                    b.Navigation("Bank");

                    b.Navigation("TypeDeposit");

                    b.Navigation("TypeSum");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Product", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Card", "Card")
                        .WithMany("Products")
                        .HasForeignKey("CardId")
                        .HasConstraintName("fk_products_cards_card_id");

                    b.HasOne("CRMBanks.Core.Entities.Credit", "Credit")
                        .WithMany("Products")
                        .HasForeignKey("CreditId")
                        .HasConstraintName("fk_products_credits_credit_id");

                    b.HasOne("CRMBanks.Core.Entities.Deposit", "Deposit")
                        .WithMany("Products")
                        .HasForeignKey("DepositId")
                        .HasConstraintName("fk_products_deposits_deposit_id");

                    b.Navigation("Card");

                    b.Navigation("Credit");

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Request", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Product", "Product")
                        .WithMany("Requests")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_requests_products_product_id");

                    b.HasOne("CRMBanks.Core.Entities.Region", "Region")
                        .WithMany("Requests")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_requests_regions_region_id");

                    b.HasOne("CRMBanks.Core.Entities.TypeProduct", "TypeProductinfo")
                        .WithMany("Requests")
                        .HasForeignKey("TypeProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_requests_type_products_type_product_id");

                    b.Navigation("Product");

                    b.Navigation("Region");

                    b.Navigation("TypeProductinfo");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.RequestAction", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Bank", null)
                        .WithMany("RequestActions")
                        .HasForeignKey("BankId")
                        .HasConstraintName("fk_request_actions_banks_bank_id");

                    b.HasOne("CRMBanks.Core.Entities.Request", "Request")
                        .WithMany("RequestActions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_actions_requests_request_id");

                    b.HasOne("CRMBanks.Core.Entities.User", "Users")
                        .WithMany("RequestActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_actions_users_user_id");

                    b.Navigation("Request");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeProduct", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.TypeCredit", "TypeCredit")
                        .WithMany("TypeProducts")
                        .HasForeignKey("TypeCreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_type_products_type_credits_type_credit_id");

                    b.HasOne("CRMBanks.Core.Entities.TypeDeposit", "TypeDeposit")
                        .WithMany("TypeProducts")
                        .HasForeignKey("TypeDepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_type_products_type_deposits_type_deposit_id");

                    b.Navigation("TypeCredit");

                    b.Navigation("TypeDeposit");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.User", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Bank", "Bank")
                        .WithMany("Users")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_banks_bank_id");

                    b.HasOne("CRMBanks.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Bank");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RegionUser", b =>
                {
                    b.HasOne("CRMBanks.Core.Entities.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_user_regions_regions_id");

                    b.HasOne("CRMBanks.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_user_users_users_id");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Bank", b =>
                {
                    b.Navigation("RequestActions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Card", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Credit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Deposit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Product", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Region", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Request", b =>
                {
                    b.Navigation("RequestActions");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeCredit", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("TypeProducts");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeDeposit", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("TypeProducts");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeProduct", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.TypeSum", b =>
                {
                    b.Navigation("Credits");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("CRMBanks.Core.Entities.User", b =>
                {
                    b.Navigation("Auth2Fs");

                    b.Navigation("RequestActions");
                });
#pragma warning restore 612, 618
        }
    }
}
